services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
  redis_bp:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
